version: 2

jobs:
  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/linnv
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: go test ./...
