version: 2

jobs:
  build:
    docker:
      - image: golang:1.21
    working_directory: /go/src/github.com/linnv/logx
    steps:
      - checkout
      - run:
          name: "Run Test"
          command: go test ./...
